// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restraurant.Data;

#nullable disable

namespace Restraurant.Migrations
{
    [DbContext(typeof(MenuContext))]
    [Migration("20251024175507_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restraurant.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://example.com/spaghetti.jpg",
                            Name = "Spaghetti Bolognese",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://example.com/caesar.jpg",
                            Name = "Caesar Salad",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://example.com/margherita.jpg",
                            Name = "Margherita Pizza",
                            Price = 10.99m
                        });
                });

            modelBuilder.Entity("Restraurant.Models.DishIngredient", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.HasKey("DishId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("dishIngredients");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            IngredientId = 1
                        },
                        new
                        {
                            DishId = 1,
                            IngredientId = 2
                        },
                        new
                        {
                            DishId = 1,
                            IngredientId = 3
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 4
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 5
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 6
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 7
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 8
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 9
                        });
                });

            modelBuilder.Entity("Restraurant.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Spaghetti"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ground Beef"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tomato Sauce"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Lettuce"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Croutons"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Caesar Dressing"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pizza Dough"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Tomato"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Mozzarella Cheese"
                        });
                });

            modelBuilder.Entity("Restraurant.Models.DishIngredient", b =>
                {
                    b.HasOne("Restraurant.Models.Dish", "Dish")
                        .WithMany("DishIngredients")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restraurant.Models.Ingredient", "Ingredient")
                        .WithMany("DishIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Restraurant.Models.Dish", b =>
                {
                    b.Navigation("DishIngredients");
                });

            modelBuilder.Entity("Restraurant.Models.Ingredient", b =>
                {
                    b.Navigation("DishIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
